### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ivomarino** [johanmeiring/ansible-sftp#26]
on line https://github.com/johanmeiring/ansible-sftp/blob/master/tasks/main.yml#L64 the setting probably should be `0770`, if not the user cannot create new files and folders. Correct or am I doing something wrong? thanks.

**Comment by johanmeiring** [comment]
As far as I understand, the permissions must be `0750` in order for chrooting to work properly.  Check out https://askubuntu.com/a/49284 as a reference for this.  I'm very open to being proven wrong though :)

**Comment by ivomarino** [comment]
thanks for feedback and you’re right, I’ve updated changes, only thing is that users can this way just write into subfolders in the chroot, which I create now, hope it’s correct that way, thanks for infos;)
