### ISSUE TITLE
custom home path for users

### ISSUE THREAD

**Issue by talset** [johanmeiring/ansible-sftp#30]
I would like to be able to change the home directory of my user (https://github.com/johanmeiring/ansible-sftp/blob/master/tasks/main.yml#L59) in order to chroot into existing directory instead of having all under sftp_home_partition.

Would it be possible to have by default sftp_home or item.home if defined

**Comment by johanmeiring** [comment]
This has been implemented, but I neglected to close this issue.  Closing it now, but please let me know if the solution did not solve your particular problem.
