### ISSUE TITLE
Can you suggest a SSH hardening role that is compatible with ansible-sftp?

### ISSUE THREAD

**Issue by thbar** [johanmeiring/ansible-sftp#32]
Since you are maintaining this role, I wonder if you are using a specific SSH hardening role that would be compatible with it?

For most of my machines, I use https://github.com/dev-sec/ansible-ssh-hardening, which completely rewrites the sshd config, and most roles I've found do the same.

As such, using `ansible-sftp` with it will mean that the first role will erase the SFTP setup that your role provide, then your role will set it up again, generating changes during the run.

Do you have any suggestion of hardening role for which this wouldn't happen?

Thanks! (happy to create a little documentation PR later if there is something worth sharing).

**Comment by johanmeiring** [comment]
Hi @thbar.  To be honest with you, I'm not currently actually using my own role in production anywhere at the moment (I left the company for whom the work was originally done a few years ago).  As such, I do not currently use this alongside an SSH hardening role, though it's plain to see where the problems you're experiencing come in, unfortunately.

Currently, I don't see an easy solution to this.  The two obvious options are:

1. SSH hardening roles should not overwrite `sshd_config` in totality, but should rather perform regex-based search-and-replace (or something similar).  However, I realise expecting them to do this is not realistic :-)
2. `ansible-sftp` should mimic the config options and behaviours of popular SSH hardening roles, and take care of `sshd_config` in totality.  I'm open to this option, but one clear disadvantage would be that we'd be making it more difficult for other roles to manipulate `sshd_config` safely and with "confidence".

If some of the other contributors and/or users of this role would like to voice their opinion they are more than welcome to do so.  I'm undecided at the moment.

**Comment by thbar** [comment]
@johanmeiring thanks for the feedback! At the moment, I'll just keep using your role (thanks again for this) and will add my own hardening which modifies the config.

I'll leave this open for a while to gather more feedback from potential contributors, though!

**Comment by cnotin** [comment]
Same issue here! Thanks to both of you for discussing this.
I don't have any suggestion unfortunately

**Comment by cnotin** [comment]
What about /etc/ssh/sshd_config.d/*.conf ? Would it work?

**Comment by johanmeiring** [comment]
I think that would definitely work, and I wish it was available when the role was originally created because it would have solved so many issues.  However, it appears to be a relatively new feature in sshd (from around v8.3p1 as far as I can see), so it will only be available on Ubuntu 20.04+, and it doesn't seem to be available on default installs of e.g. CentOS 8 yet (speaking under correction).  I would LOVE to use this, but it would severely limit the reach of the role at this point.  But it's definitely worth future consideration.

**Comment by cnotin** [comment]
Oh yes indeed if that's too new we cannot use it... Thanks for checking this!
