### ISSUE TITLE
Password hash

### ISSUE THREAD

**Issue by bee-keeper** [johanmeiring/ansible-sftp#36]
Hello,

Regarding the password hash the Readme states "A password hash for the user to login with" and the example given is: 

`password: "$1$salty$li5TXAa2G6oxHTDkqx3Dz/" # passpass`

What are the commands to create compatible hashes from user chosen passwords so that they can be documented and added to the Readme?

Thanks,

**Comment by johanmeiring** [comment]
Hey @bee-keeper :-)

This should work:

```bash
$ openssl passwd -1 -salt salty passpass
$1$salty$li5TXAa2G6oxHTDkqx3Dz/
```

Hope that helps.

**Comment by bee-keeper** [comment]
Nice one, thanks!  If you think it's worthwhile I can make a PR to the Readme?

**Comment by johanmeiring** [comment]
Absolutely, 🐝  my guest.

**Comment by bee-keeper** [comment]
https://github.com/johanmeiring/ansible-sftp/pull/37
