### ISSUE TITLE
chroot not working

### ISSUE THREAD

**Issue by juanluisbaptiste** [johanmeiring/ansible-sftp#46]
Hi,

I'm testing your role but it seems that the user chroot is not working. I copy pasted the example in the README file, and after logging in with the user sally I can see the contents of the root directory:

```
$ sftp -i ~/.ssh/id_rsa sally@xxx.xxx.xxx.xxx
Connected to xxx.xxx.xxx.xxx
sftp> pwd
Remote working directory: /var/tmp/sally
sftp> cd /
sftp> ls
bin              boot             dev              etc              home             initrd.img       initrd.img.old   lib              lib64            lost+found       media            
mnt              opt              proc             root             run              sbin             snap             srv              sys              tmp              usr              
var              vmlinuz          vmlinuz.old

```

Does it work for you ?

**Comment by juanluisbaptiste** [comment]
I found what is happening. If the playbook fails for example because I put the incorrect ssh key for a user, then fix the playbook and run it again, sshd is not restarted, hence sftp configuration is not applied. After reloading the sshd service the chroot works. But if the playbook runs without problems the first time then the chrooting works, BUT, not for the _sally_ account on the example. Looking at `/var/log/auth.log` the session fails with this error:

```
Aug 24 22:43:28 swarm-manager-prod-1 systemd-logind[808]: New session 19 of user sally.
Aug 24 22:43:28 swarm-manager-prod-1 systemd: pam_unix(systemd-user:session): session opened for user sally by (uid=0)
Aug 24 22:43:29 swarm-manager-prod-1 sshd[31351]: fatal: bad ownership or modes for chroot directory component "/var/tmp/"
Aug 24 22:43:29 swarm-manager-prod-1 sshd[31272]: pam_unix(sshd:session): session closed for user sally
Aug 24 22:43:29 swarm-manager-prod-1 systemd-logind[808]: Removed session 19.

```

Would it work if the tasks that modify the sshd config file are run after the users and groups are created and ssh keys uploaded ? that way even if one of those tasks fail, after they are fixed then the notification to the sshd handler will be sent anyways, avoiding leaving a partially applied configuration.

Also the other example account, peter does not work, as by default password logins come disabled on ubuntu.

**Comment by mrexojo** [comment]
Hi @juanluisbaptiste , I just to commit a pull request with a fix

**Comment by juanluisbaptiste** [comment]
Hi @mrexojo,

Thanks for the PR, it fixes one of three issues listed here, one why the example sally account does not work and that is fixed with your PR, another is that if the playbook fails after sshd configuration is modified sshd service is not restarted and configuration is not applied (my main concern), and the peter example account also does not work because sshd comes with password login disabled ny default.

I can split this issue to handle each of them separately it you want.

**Comment by johanmeiring** [comment]
Hi folks!

@mrexojo Thanks for the PR, I'll look at it and likely merge it shortly.

@juanluisbaptiste Thanks for bringing this to my attention.  I'm less concerned about the peter example not working (probably a consequence of defaults changing across Ubuntu versions over time), but your other problem is definitely a potential issue.  Rearranging many of the tasks would make sense, along with calling the handler on more of the tasks, which is more or less what you're suggesting if I understand correctly.  I'll try to make some time for that tomorrow.

**Comment by juanluisbaptiste** [comment]
Hi @johanmeiring Excellent, thanks !!

**Comment by johanmeiring** [comment]
My apologies, folks.  I could not get around to this yet.  Hopefully soon.

**Comment by johanmeiring** [comment]
@juanluisbaptiste I've made a change that will cause the sshd to be restarted with each and every run of the playbook.  Please let me know if the problem persists after this change :-)

**Comment by juanluisbaptiste** [comment]
Thank you.

**Comment by johanmeiring** [comment]
@juanluisbaptiste I've unfortunately had to revert the work that was done on the chroot issue, as it was causing problems here: https://github.com/johanmeiring/ansible-sftp/issues/49.  Can you confirm if the chroot issue is in fact still present for you on v3.1.3 ?  If so, we'll need to reopen this issue and find another way to solve it.
