### ISSUE TITLE
`sftp_directories` is creating directories at "/home/user/ "

### ISSUE THREAD

**Issue by hoangmnsd** [johanmeiring/ansible-sftp#51]
As i see, when I specify : 
`sftp_start_directory`: "/datadrive"
`sftp_directories` : "/datadrive/error"

It is creating directories at "/home/user/datadrive/error"
what i want is creating directories at "/datadrive/error"

What should I do to deal with it?

**Comment by johanmeiring** [comment]
Hi @hoangmnsd ... have you looked at setting the `sftp_home_partition` variable to `/datadrive` ?  Could that solve the problem in your case?

**Comment by hoangmnsd** [comment]
sorry, it's my mistake. I am going to close this issue.
