### ISSUE TITLE
Change regular expression in SFTP-Server | Alter sftp subsystem entry

### ISSUE THREAD

**Issue by kedailey21** [johanmeiring/ansible-sftp#8]
The regular expression used to find the existing `Subsystem sftp` entry is dangerous.  You should probably change it to

`regexp="^Subsystem(\s+)sftp`

That way, it will find the line regardless of how much whitespace is in the line.  Otherwise, if the current line had, say, a tab between `Subsystem` and `sftp`, it would insert a new line, and the `ssh` service would fail to restart because of multiple `sftp` `Subsystem`s defined in the config file, potentially locking you completely out of the server.

**Comment by johanmeiring** [comment]
Thanks @kedailey21, you're totally right.  I've pushed the suggested fix and create tag v0.9.4... hopefully ansible-galaxy will pick it up soon, otherwise I'll try to force it.
